Python3
collective/Products.PloneLDAP pull request #10
Opened 2020-02-12 14:01 UTC by ale-rt

2020-02-22 10:51 UTC, mauritsvanrees requested changes
Thanks for working on this.
I have one small change request, see comment. After fixing that, it is safe to merge.

2020-02-22 10:51 UTC, mauritsvanrees commented on Products/PloneLDAP/_utils.py
> +zope.deferredimport.deprecated(
This is in an `_utils.py` file, so it is implicitly marked as unstable due to starting with an underscore.
I can't imagine anyone importing it from here instead of from CMFPlone, so for me it would have been fine to just remove it.
But now that you have done the work, it is fine to keep it. :-)

2020-02-22 10:51 UTC, mauritsvanrees commented on Products/PloneLDAP/property.py
> +                    if isinstance(value, six.text_type):
On Python 2 this changes the behavior: `basestring` is`str` and `unicode`, but `six.text_type` is only `unicode`, so you lose the `str`.
It could be that in this case it is fine, but I would not count on it.
Better replace it with `six.string_types`.
See [six.readthedocs.io](https://six.readthedocs.io/#six.string_types). (And yes, I have to look that up too, because I don't have all the various six aliases in my head.)

2020-02-22 10:53 UTC, mauritsvanrees approved these changes

2020-02-22 10:53 UTC, merged

2020-02-22 10:54 UTC, mauritsvanrees commented
My change request was not needed after all. I have merged. Thanks!

2020-02-24 08:02 UTC, ale-rt commented
BTW I am not using Products.PloneLDAP in production with Python3, not sure if @cdw9 (which created this branch) is doing so. 
When I checked it I found a lot was still to done.

2020-02-24 08:08 UTC, mauritsvanrees commented
I am not using it either. I recommend `pas.plugins.ldap`.

2020-02-24 14:13 UTC, cdw9 commented
I was not able to get it completely working yet. On the last site I tried, we did end up using pas.plugins.ldap. 

We do have one client whose AD did not play well with pas.plugins.ldap, so I was hoping to get PloneLDAP working, but they don't have the budget for us to spend time on it.